pom_model:

  # General model params
  dropout_rate: 0.1

  # Molecule blocks
  mol_encoder:
    type: "gnn"  # ["linear", "gnn"]
    output_dim: 196
    gnn:
      global_dim: ${pom_model.mol_encoder.output_dim}
      hidden_dim: 320
      depth: 4

  # Fraction agg
  fraction_aggregation:
    type: "concat"  # ["concat", "multiply", "film"]
    film:
      activation: "sigmoid"  # ["sigmoid", "relu"]
      output_dim: ${pom_model.mol_encoder.output_dim}

  # Prediction head
  regressor:
    type: "mlp"  # ["mlp", "physics_based"]

    hidden_dim: 100
    num_layers: 0   # a GLM

    mlp:
      output_dim: 138

# Data
dataset:
  name: 'gslf'
  task: ["gslf"]
  featurization: "molecular_graphs" # ["molecular_graphs", "molt5_embeddings", "rdkit2d_normalized_features"]

# Scheduler
loss_type: "bce"
optimizer_type: "adam"
lr_mol_encoder: 1e-4
weight_decay: 0

# Trainer
seed: 42
root_dir: pom_gslf_glm
num_workers: 1
max_epochs: 1000
batch_size: 128
device: "cuda"
early_stopping: True
early_stopping_minimize: False
patience: 100
