program: hp_search_pom.py
name:
method: bayes

metric:
  goal:
  name:

parameters:

  pom_model:
    parameters:
      dropout_rate:
        values: [0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4, 0.45, 0.5]

      mol_encoder:
        parameters:
          type:
            value: "gnn"
          
          output_dim:
            values: [96, 128, 256]
  
          gnn:
            parameters:
              hidden_dim:
                values: [64, 128, 192, 256, 320]
              depth:
                values: [2, 3, 4]

      fraction_aggregation:
        parameters:
          type:
            values: ["concat", "multiply", "film"]
          film:
            parameters:
              activation:
                values: ["sigmoid", "relu"]

      regressor:
        parameters:
          type:
            value: "mlp"
          hidden_dim:
            values: [64, 128, 192, 256, 320]
          num_layers:
            values: [1, 2, 3]

  dataset:
    parameters:
      featurization:
        values: ["molecular_graphs"]

  lr_mol_encoder:
    values: [8e-5, 5e-5, 1e-4, 5e-4, 8e-4, 1e-3, 5e-3, 1e-2]

  loss_type:
    values: ["mae", "mse"]

command:
  - ${env}
  - python
  - ${program}
  - "default.yaml"